---
- name: Gather facts on all hosts
  hosts: mm
  tasks:
  - setup:
    gather_subnet:
      - "all"
  tags:
  - always

- name: Deploys docker, docker-compose & dependencies
  hosts: mm
  become: yes
  roles:
    - role: docker
  tags:
    - docker
  
# - name: Deploys Postgres
#   hosts: mm
#   become: yes
#   roles: 
#     - role: postgres
#   tags:
#    - postgres

# - name: Deploys mm
#   hosts: mm
#   become: yes
#   roles:
#     - role: mm
#   tags:
#     - mm