---
- name: Gather facts on all hosts
  hosts: mattermost
  tasks:
  - setup:
    gather_subnet:
      - "all"
  tags:
  - always

- name: Deploys docker, docker-compose & dependencies
  hosts: mattermost
  become: yes
  roles:
    - role: docker
  tags:
    - docker
  
- name: Deploys Postgres and Mattermost
  hosts: mattermost
  become: yes
  roles: 
    - role: mattermost
  tags:
   - mattermost